// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNouyaaHzfM71A-nc5DYs0Zqc1JfoU3Qo',
    appId: '1:1028131929489:web:30249a7c6c88b713bf6e30',
    messagingSenderId: '1028131929489',
    projectId: 'moodly-18057',
    authDomain: 'moodly-18057.firebaseapp.com',
    storageBucket: 'moodly-18057.firebasestorage.app',
    measurementId: 'G-RWTRFHJGDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdk69IkhAAsZ224MIcJZis9BD4q4szweU',
    appId: '1:1028131929489:android:a94e9c6921e45e20bf6e30',
    messagingSenderId: '1028131929489',
    projectId: 'moodly-18057',
    storageBucket: 'moodly-18057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPPpO2pZ2O1ovDl1tiGcYBJSh2ijwSeU',
    appId: '1:1028131929489:ios:a4f555fd8d582ba0bf6e30',
    messagingSenderId: '1028131929489',
    projectId: 'moodly-18057',
    storageBucket: 'moodly-18057.firebasestorage.app',
    iosBundleId: 'com.example.moodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPPpO2pZ2O1ovDl1tiGcYBJSh2ijwSeU',
    appId: '1:1028131929489:ios:a4f555fd8d582ba0bf6e30',
    messagingSenderId: '1028131929489',
    projectId: 'moodly-18057',
    storageBucket: 'moodly-18057.firebasestorage.app',
    iosBundleId: 'com.example.moodly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNouyaaHzfM71A-nc5DYs0Zqc1JfoU3Qo',
    appId: '1:1028131929489:web:169662e95093f227bf6e30',
    messagingSenderId: '1028131929489',
    projectId: 'moodly-18057',
    authDomain: 'moodly-18057.firebaseapp.com',
    storageBucket: 'moodly-18057.firebasestorage.app',
    measurementId: 'G-79PZ9FF077',
  );
}
