name: moodly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.2.4
  image_picker: ^1.2.1
  http: ^1.6.0
  url_launcher: ^6.2.4
  firebase_storage: ^13.3.0
  shared_preferences: ^2.5.5
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.6
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  google_mobile_ads: ^5.0.0
  gal: ^2.3.2
  home_widget: ^0.7.0+1
  flutter:
    sdk: flutter
  image_cropper: ^8.0.2
  flutter_quill: ^11.5.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/google.png
    - assets/icon/facebook.png
    - assets/icon/image1.png
    - assets/icon/image2.png
    - assets/icon/image3.png
    - assets/icon/image4.png
    - assets/icon/images/
    - assets/profile_pic/
    - assets/icons/
    - assets/homepage_assets/
    - assets/mascots/
    - assets/icons/navbar/
    - assets/images/
    - assets/icons/login/
    - assets/emoji/
    - assets/streak_badges/
