name: moodly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  firebase_core: ^4.7.0
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  shared_preferences: ^2.5.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/profile_pic/
    - assets/icons/
    - assets/icons/navbar/
    - assets/images/
